const data = {
    products: [
        {
            _id: '1',
            name: 'T Shirt',
            brand: 'Nike',
            category : 'Shirts',
            image : '/images/p1.jpg',
            price:160,
            rating : 4.8,
            reviews : 8,
            description : 'High quality shirt',
            countInStock: 4,
        },
        {
            _id : '2',
            name : 'Summer T Shirt',
            brand : 'Nike',
            category : 'Shirts',
            image : '/images/p1.jpg',
            price:165,
            rating : 4.8,
            reviews : 8,
            description : 'High quality shirt',
            countInStock: 4,
        },
        {
            _id : '3',
            name : 'nice T Shirt',
            brand : 'Nike',
            category : 'Shirts',
            image : '/images/p1.jpg',
            price:180,
            rating : 3,
            reviews : 3,
            description : 'High quality shirt',
            countInStock: 4,
        },
        {
            _id : '4',
            name : 'Red Shirt',
            brand : 'Nike',
            category : 'Shirts',
            image : '/images/p1.jpg',
            price:160,
            rating : 4.8,
            reviews : 8,
            description : 'High quality shirt',
            countInStock: 4,
        },
        {
            _id : '5',
            name : 'Blue Shirt',
            brand : 'Nike',
            category : 'Shirts',
            image : '/images/p1.jpg',
            price:160,
            rating : 4,
            reviews : 8,
            description : 'High quality shirt',
            countInStock: 4,
        },
        {
            _id : '6',
            name : 'Slim Shirt',
            brand : 'Nike',
            category : 'Shirts',
            image : '/images/p1.jpg',
            price:160,
            rating : 4.8,
            reviews : 8,
            description : 'High quality shirt',
            countInStock: 0,
        },
    ],
};

export default data;